{
 "title": "Prometheus Android Exporter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Miscellaneous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Android system version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(android_system_info)without(backfill)",
     "legendFormat": "{{os_release}}"
    }
   ]
  },
  {
   "title": "Cpu core count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(android_system_info)without(backfill)",
     "legendFormat": "{{cpu_core_count}}"
    }
   ]
  },
  {
   "title": "Android system uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "android_uptime_seconds" }
   ]
  },
  {
   "title": "Android device model",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(android_system_info)without(backfill)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Manufacturer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(android_system_info)without(backfill)",
     "legendFormat": "{{manufacturer}}"
    }
   ]
  },
  {
   "title": "Scrape duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(android_scrape_duration_seconds)without(backfill)"
    }
   ]
  },
  { "title": "Hardware sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Android heading sensor accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "avg(android_sensor_heading_accuracy_degrees) without(backfill)"
    }
   ]
  },
  {
   "title": "Android heading sensor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "avg(android_sensor_heading_degrees)without(backfill)"
    }
   ]
  },
  {
   "title": "Andriod proximity sensor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "avg(android_sensor_proximity_metres) without(backfill) * 10000"
    }
   ]
  },
  {
   "title": "Android hinge angle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "avg(android_sensor_hinge_angle_degrees)without(backfill)"
    }
   ]
  },
  {
   "title": "Android accelerometer sensor",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "expr": "avg(android_sensor_accelerometer) without(backfill)"
    }
   ]
  },
  {
   "title": "Android magnetic field sensor",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "μT" } },
   "targets": [
    {
     "expr": "avg(android_sensor_magnetic_field_tesla) without(backfill) * 1000000"
    }
   ]
  },
  {
   "title": "Android sensor gravity acceleration",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "expr": "avg(android_sensor_gravity_acceleration)without(backfill)"
    }
   ]
  },
  {
   "title": "Android linear acceleration sensor",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "expr": "avg(android_sensor_linear_acceleration)without(backfill)"
    }
   ]
  },
  {
   "title": "Android pressure sensor",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "avg(android_sensor_pressure_pascal)without(backfill) / 100.0"
    }
   ]
  },
  {
   "title": "Android ambient light sensor",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "expr": "avg(android_sensor_ambient_light_lux)without(backfill)"
    }
   ]
  },
  {
   "title": "Ambient temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(android_sensor_ambient_temperature_celsius)without(backfill)"
    }
   ]
  },
  {
   "title": "Android round vector sensor data",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "avg(android_sensor_rotation_vector)without(backfill)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "WiFi status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "android_wifi_connected" }
   ]
  },
  {
   "title": "Cellular network status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(android_cellular_network_connected)without(backfill)"
    }
   ]
  },
  { "title": "PushProx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "PushProx scrape errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "rate(avg(pushprox_client_scrape_errors_total) without(backfill)[5m])"
    }
   ]
  },
  {
   "title": "PushProx push errors rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 96 },
   "targets": [
    {
     "expr": "rate(avg(pushprox_client_push_errors_total) without (backfill)[5m])"
    }
   ]
  },
  {
   "title": "PushProx poll errors rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 96 },
   "targets": [
    {
     "expr": "rate(avg(pushprox_client_poll_errors_total) without(backfill)[5m])"
    }
   ]
  },
  { "title": "Battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Current battery percentage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(android_battery_charge_ratio{}) without(backfill) * 100"
    }
   ]
  },
  {
   "title": "Battery status",
   "type": "stat",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 107 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(android_battery_is_charging)without(backfill)"
    }
   ]
  }
 ]
}