//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: remote-write.proto

package protogen;

@kotlin.jvm.JvmSynthetic
public inline fun label(block: protogen.LabelKt.Dsl.() -> kotlin.Unit): protogen.RemoteWrite.Label =
  protogen.LabelKt.Dsl._create(protogen.RemoteWrite.Label.newBuilder()).apply { block() }._build()
public object LabelKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protogen.RemoteWrite.Label.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: protogen.RemoteWrite.Label.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): protogen.RemoteWrite.Label = _builder.build()

    /**
     * <code>string name = 1;</code>
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <code>string name = 1;</code>
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * <code>string value = 2;</code>
     */
    public var value: kotlin.String
      @JvmName("getValue")
      get() = _builder.getValue()
      @JvmName("setValue")
      set(value) {
        _builder.setValue(value)
      }
    /**
     * <code>string value = 2;</code>
     */
    public fun clearValue() {
      _builder.clearValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun protogen.RemoteWrite.Label.copy(block: protogen.LabelKt.Dsl.() -> kotlin.Unit): protogen.RemoteWrite.Label =
  protogen.LabelKt.Dsl._create(this.toBuilder()).apply { block() }._build()
